### PR TITLE
feat: add spinner methods

### PR DESCRIPTION
**Pull request by mdonnalley**
Expose spinner related methods in `SfCommand`

#### Usage

```typescript
import { SfCommand } from '@salesforce/sf-plugins-core';
import { sleep } from '@salesforce/kit';

export default class MyCommand extends SfCommand {
  public async run(): Promise<void> {
    this.spinner.start('Doing some stuff');
    await sleep(5000);
    this.spinner.stop('Success');
  }
}
```

@W-10330464@

### CODE REVIEW

**Comment by peternhale** [comment]
@mdonnalley would it make sense to use deploy/retrieve plugins code for cli.action and progress bar inspiration for this need? Seems like something that will be needed.

https://github.com/salesforcecli/plugin-deploy-retrieve-metadata/blob/main/src/commands/retrieve/metadata.ts
https://github.com/salesforcecli/plugin-deploy-retrieve-metadata/blob/main/src/utils/progressBar.ts

**Comment by mdonnalley** [comment]
> https://github.com/salesforcecli/plugin-deploy-retrieve-metadata/blob/main/src/utils/progressBar.ts

@peternhale I just updated the `Spinner` class based on that example. It should be a straightforward replacement

```typescript
retrieve.onUpdate((data) => {
  this.spinner.status = mdTrasferMessages.getMessage(data.status);
});

// any thing else should stop the progress bar
retrieve.onFinish((data) => this.spinner.stop(mdTrasferMessages.getMessage(data.response.status)));

retrieve.onCancel((data) => this.spinner.stop(mdTrasferMessages.getMessage(data.status)));

retrieve.onError((error: Error) => {
  this.spinner.stop(error.name);
  throw error;
});

this.spinner.start(messages.getMessage('RetrieveTitle'));
```

For the progress bar, yes I think plugin-deploy-retrieve-metadata would be the main inspiration for how we implement it in sf-plugins-core. But I'd rather leave that to it's own effort

**Review by peternhale — APPROVED** [review]

**Review by RodEsp — CHANGES_REQUESTED** [review]
I'd like to see this documented in the README before it's merged.

**Comment by mdonnalley** [comment]
> I'd like to see this documented in the README before it's merged.

@RodEsp since the README is currently empty I'd prefer to create a separate WI to write one. I think that makes more sense than adding a single bullet point right now

**Pull request merged**
